litl/backoff

- README.rst
- backoff.py
- backoff_tests.py
This makes the max_tries kwarg on on_exception and on_predicate
optionally accept a callable to be evaluated at runtime rather
than a fixed value.
Similarly, wait_gen_kwargs also optionally accept callables to be
evaluated before passing into the wait_gen. This means that all
current kwargs on backoff.expo, backoff.fibo, backoff.constant now
accept callables, and also that all future and user-space wait
generators will as well.
This addresses https://github.com/litl/backoff/issues/10
> Support runtime configuration with optionally callable kwargs

- backoff.py
This behavior, while convenient for debugging in some cases, has the
potential to leak sensitive information. It's not a good default.
The full details of the function invocation are still available in the
on_backoff and on_giveup handlers, so this information can still be
logged by way of custom handlers.
This addresses: https://github.com/litl/backoff/issues/16
> Don't log retried args and kwargs by default

- Makefile
- backoff.py
This creates a few helper functions that are called by both
`on_exception` and `on_predicate`. If nothing else this makes
those implementations less verbose and perhaps a little easier
to follow the control flow.
> Factor out some helper functions

- README.rst
See http://aiohttp.readthedocs.io/en/stable/migration.html which states
"All exceptions are moved from aiohttp.errors module to top level
aiohttp module."
> Update README with aiohttp 2.x code

- backoff/_decorator.py
- tests/python34/test_backoff_async.py
- tests/test_backoff.py
> fix checking for running sync version in coroutine in case when event loop is not set

- backoff/_common.py
Commit 05b918f ("Refactor into submodules", 2017-01-23) moved the logger
declaration from __init__ to _common. As a result, the logger name is no
longer backoff but backoff._common. This commit set its back to
backoff as documented.
I believe this change should come with tests, but I did not provide any. Sorry.
> Use documented logger name

- README.rst
- backoff/_async.py
- backoff/_common.py
- backoff/_decorator.py
- backoff/_sync.py
- tests/python34/test_backoff_async.py
- tests/test_backoff.py
This addresses https://github.com/litl/backoff/issues/43
The core issue is that with `full_jitter`, `max_tries` is no longer a
reliable way to control the total retry time. This adds a similar
`max_time` keyword argument which triggers a giveup after a total
elapsed amount of time rather than a set number of retries.
Further, since full_jitter is actually the default behavior, you
probably generally want to use `max_time` rather than `max_tries` so
this updates the examples in the README to show that.
> Add max_time keyword argument

- .travis.yml
- pyproject.toml
Python 3.4 build is broken on travis because of a poetry dep.
This version of python is end of lifed so we can just remove it.
> Remove python 3.4 support

- .gitignore
- .travis.yml
- backoff/__init__.py
- backoff/_async.py
- pyproject.toml
- tests/python35/test_backoff_async.py
We had previously dropped support for python 3.4 but it turns out we
were still using some 3.4-isms by using the asyncio.coroutine
decorator to wrap normal functions. This replaces those instance with
the now supported (since 3.5) `async/await` syntax.
This gets rid of warnings that occcured at runtime and during unit
tests when running under python 3.8.
This address https://github.com/litl/backoff/issues/81
> Support python 3.8

- backoff/_common.py
There is a small typo in backoff/_common.py.
Should read `allotted` rather than `alloted`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, alloted -> allotted

- backoff/_common.py
- backoff/_decorator.py
- tests/test_backoff.py
Allow configuring log level for backoff and give up events by passing `backoff_log_level` and `giveup_log_level` parameters.
> Make logging level for backoff and give up events configurable

- README.rst
> Fix README typo: afters -> after

- README.rst
Replace logging `add_handler` by `addHandler'` when configuring logger
Tested with logging version:
```
>>> logging.__version__
'0.5.1.2'
```
> fix logging usage in Readme

- README.rst
- aiohttp's `ClientSession` interface for making requests [defaults the property](https://docs.aiohttp.org/en/stable/client_reference.html) `raise_for_status` to `False`.
- So response errors (non-200 status) don't automatically raise exceptions and therefore won't trigger `@backoff.on_exception` decorator for the async/aiohttp example code in the README.
- Update README aiohttp example code to set  `raise_for_status=True`.
> update readme aiohttp example to set raise_for_status=True

- README.rst
The README includes a couple typos referencing to a non-existent module `requests.exception`.
This commit fixes the typos.
> README: fix typo in requests.exceptions

- backoff/_decorator.py
- backoff/_typing.py
The original `Callable` return type on decorators hid the call signature of the inner (argument-less) decorator, as well as the decorated function itself.
This PR uses a Callable-bound `TypeVar` instead and replicates the decorated function's signature in the decorator's return value.
*Example of the Pylance type checker still recognizing the type of a function after it was decorated.*
This avoids type checking errors such as Mypy's "Untyped decorator makes function "resilient_foo" untyped" warning.
> Prevent decorators from hiding the decorated function's signature

- README.rst
- backoff/_async.py
- backoff/_decorator.py
- backoff/_sync.py
- tests/test_backoff.py
- tests/test_backoff_async.py
https://github.com/litl/backoff/issues/118
Implement feature to optionally disable raising of exceptions on giveup.
> Feature - Raise on Giveup

- backoff/_decorator.py
- backoff/_typing.py
- Make _MaybeLogger type optional
- Update decorators on_success, on_backoff, on_giveup parameters (add iterable of callable)
> Update type annotations

- README.rst
AFAIK the default jitter algorithm is the `full_jitter` making the polling interval vary between 0 and 1 sec in the given example.
If someone wants to have a fixed polling interval/frequency as the lead of this example suggests then jitter should be disabled.
> disable jitter in polling example.

- backoff/_sync.py
- tests/test_backoff.py
- tests/test_backoff_async.py
Changes backoff to dynamically get the `max_tries` and `max_time` values for every new call and always try to evaluate. 
Avoid caching the first obtained value for all executions.
See #160
> Get max_tries/max_time values for every call fixes #160

- README.rst
- backoff/_async.py
- backoff/_sync.py
- tests/test_backoff.py
- tests/test_backoff_async.py
Closes #145.
Possibly also closes #72, but I'm not 100% because it does not address @michaeltcoelho's second point about the empty `raise` statement.
> Add exception to details dict in on_backoff() and on_giveup() handlers

- README.rst
Thank you for maintaining this project!
I couldn't find usage of `backoff.runtime` documented anywhere and only found references in the changelog and release notes. Having this in the readme might help folks find it more easily.
> docs: Document `backoff.runtime` in readme

- backoff/__init__.py
- backoff/_async.py
- backoff/_common.py
- backoff/_decorator.py
- backoff/_jitter.py
- backoff/_sync.py
- backoff/_typing.py
- backoff/_wait_gen.py
- backoff/types.py
- tests/common.py
- tests/test_backoff.py
- tests/test_backoff_async.py
- tests/test_jitter.py
- tests/test_types.py
- tests/test_wait_gen.py
[`pyupgrade` automatically upgrades syntax for newer versions of the language.](https://github.com/asottile/pyupgrade#pyupgrade)
`#  coding:utf-8` is a [no-op in Python 3](https://github.com/asottile/pyupgrade#-coding--comment) because all Python source files are utf-8 by default.
> pyupgrade --py37-plus **/*.py

- backoff/_decorator.py
* Add that the `max_time` is in seconds
> Update decorator's argument "max_time" description
